### ISSUE TITLE
Plugin does not install despite NetBeans running on Zulu JDK 17

### ISSUE THREAD

**Issue by jkovalsky** [philippefichet/asciidoc4netbeans#5]
I am not able to install the asciidoc4netbeans plugin [1] in NetBeans 18 despite the fact that it is running on Zulu JDK 17.0.7. The installation ends with this dependency error:

Warning - could not install some modules: JavaFX wrapper - None of the modules providing the capability org.openide.modules.jre.JavaFX could be installed. JavaFX wrapper - JavaFX libraries are missing in your JDK. Download JDK from Oracle or continue with some modules disabled. asciidoc4netbeans - None of the modules providing the capability org.openide.modules.jre.JavaFX could be installed. Another module could not be installed due to the above problems.

[1] [https://plugins.netbeans.apache.org/catalogue/?id=91](https://plugins.netbeans.apache.org/catalogue/?id=91)

This is the NetBeans configuration:

Product Version: Apache NetBeans IDE 18
Java: 17.0.7; OpenJDK 64-Bit Server VM 17.0.7+7-LTS
Runtime: OpenJDK Runtime Environment 17.0.7+7-LTS
System: Linux version 5.15.0-76-generic running on amd64; UTF-8; cs_CZ (nb)
User directory: /home/cesilko/.netbeans/18
Cache directory: /home/cesilko/.cache/netbeans/18

Please note I have the following modules enabled:

org.netbeans.modules.javafx2.platform [1.46 18-7d33005615b3c744564f3d38ab9ef14bf8c3ec44]
org.netbeans.modules.javafx2.project [1.50 18-7d33005615b3c744564f3d38ab9ef14bf8c3ec44]
org.netbeans.modules.javafx2.editor [1.41.0.12.6 18-7d33005615b3c744564f3d38ab9ef14bf8c3ec44]
org.netbeans.modules.javafx2.scenebuilder [1.37 18-7d33005615b3c744564f3d38ab9ef14bf8c3ec44]
org.netbeans.modules.javafx2.samples [1.37 18-7d33005615b3c744564f3d38ab9ef14bf8c3ec44]

**Comment by philippefichet** [comment]
Hello and thank you for your feedback :).
The Zulu JDK may not have the JavaFX part.
Can you check if you can see the javafx modules with the following command "java --list-modules"?
Example with my JDK FX Zulu:

```
"C:\Program Files\Zulu\zulu-17\bin\java" --list-modules
com.azul.crs.client@17.0.5
com.azul.tooling@17.0.5
java.base@17.0.5
java.compiler@17.0.5
[...]
javafx.base@17.0.5
javafx.controls@17.0.5
javafx.fxml@17.0.5
javafx.graphics@17.0.5
javafx.media@17.0.5
javafx.swing@17.0.5
javafx.web@17.0.5
jdk.accessibility@17.0.5
jdk.attach@17.0.5
[...]
jdk.xml.dom@17.0.5
jdk.zipfs@17.0.5
```

PS: I would like to ask for this verification, as I regularly use my plugin with netbeans 18 the "JDK FX" Zulu ;)

**Comment by jkovalsky** [comment]
cesilko@cesilko-nb:~/Software/Java/zulu_jdk17.0.7/bin$ ./java --list-modules 
java.base@17.0.7
java.compiler@17.0.7
java.datatransfer@17.0.7
java.desktop@17.0.7
java.instrument@17.0.7
java.logging@17.0.7
java.management@17.0.7
java.management.rmi@17.0.7
java.naming@17.0.7
java.net.http@17.0.7
java.prefs@17.0.7
java.rmi@17.0.7
java.scripting@17.0.7
java.se@17.0.7
java.security.jgss@17.0.7
java.security.sasl@17.0.7
java.smartcardio@17.0.7
java.sql@17.0.7
java.sql.rowset@17.0.7
java.transaction.xa@17.0.7
java.xml@17.0.7
java.xml.crypto@17.0.7
jdk.accessibility@17.0.7
jdk.attach@17.0.7
jdk.charsets@17.0.7
jdk.compiler@17.0.7
jdk.crac@17.0.7
jdk.crypto.cryptoki@17.0.7
jdk.crypto.ec@17.0.7
jdk.dynalink@17.0.7
jdk.editpad@17.0.7
jdk.hotspot.agent@17.0.7
jdk.httpserver@17.0.7
jdk.incubator.foreign@17.0.7
jdk.incubator.vector@17.0.7
jdk.internal.ed@17.0.7
jdk.internal.jvmstat@17.0.7
jdk.internal.le@17.0.7
jdk.internal.opt@17.0.7
jdk.internal.vm.ci@17.0.7
jdk.internal.vm.compiler@17.0.7
jdk.internal.vm.compiler.management@17.0.7
jdk.jartool@17.0.7
jdk.javadoc@17.0.7
jdk.jcmd@17.0.7
jdk.jconsole@17.0.7
jdk.jdeps@17.0.7
jdk.jdi@17.0.7
jdk.jdwp.agent@17.0.7
jdk.jfr@17.0.7
jdk.jlink@17.0.7
jdk.jpackage@17.0.7
jdk.jshell@17.0.7
jdk.jsobject@17.0.7
jdk.jstatd@17.0.7
jdk.localedata@17.0.7
jdk.management@17.0.7
jdk.management.agent@17.0.7
jdk.management.jfr@17.0.7
jdk.naming.dns@17.0.7
jdk.naming.rmi@17.0.7
jdk.net@17.0.7
jdk.nio.mapmode@17.0.7
jdk.random@17.0.7
jdk.sctp@17.0.7
jdk.security.auth@17.0.7
jdk.security.jgss@17.0.7
jdk.unsupported@17.0.7
jdk.unsupported.desktop@17.0.7
jdk.xml.dom@17.0.7
jdk.zipfs@17.0.7

**Comment by jkovalsky** [comment]
It's obviously missing. I am trying to install now zulu17.42.19-ca-fx-jdk17.0.7-linux_amd64.deb

**Comment by jkovalsky** [comment]
OK, my bad. Closing as user error. :-)

**Comment by philippefichet** [comment]
Thank you :)
