### ISSUE TITLE
Missing JavaFX

### ISSUE THREAD

**Issue by harrybraun** [philippefichet/asciidoc4netbeans#6]
I am very happy to have found an asciidoc plugin for netbeans. However, when I install it in Netbeans 18, Java 19 I always get the following error message:
Activation failed: Cannot enable asciidoc4netbeans[com.github.philippefichet.asciidoc4netbeans] - requires org.openide.modules.jre.JavaFX - module org.netbeans.libs.javafx > 2.22

Starting the JavaFX2 module manually was no problem, but the error message remains.
Do I need to install anything else?

Regards, 
Harry

**Comment by philippefichet** [comment]
Hello,
I'm aware of this problem: for Netbeans 18 and only this version (https://github.com/apache/netbeans/issues/6004), you need a JDK that includes Java FX.
This is (or will be) corrected in future versions of Netbeans.
You can use the Zulu JDK (https://www.azul.com/downloads/?package=jdk-fx#zulu) managed by Azul to avoid this problem.
Unfortunately, I don't have any other solution at the moment.

**Comment by philippefichet** [comment]
Fixed on Netbeans 20 from https://github.com/apache/netbeans/issues/6460
